### ISSUE TITLE
X11 Support

### ISSUE THREAD

**Issue by mjjames** [LogMeIn/logmein-linux-host#3]
Is it possible to support X11 forwarding? We'd like to be able to connect to the terminal but also on some occasions view the X11 and see what's on screen.

**Comment by matenavay** [comment]
Hi James,

The current solution only provides SSH access in the browser. The initial version was intended to be very straighforward and secure with minimal to no configuration needed on the linux machine.
We're working on some iterations to allow GUI access to a few GUI implementations, but with a pretty low capacity currently.
