### ISSUE TITLE
Just the terminal?

### ISSUE THREAD

**Issue by tomSCJE** [LogMeIn/logmein-linux-host#8]
So does this just allow for access to the terminal or would we be able to open a desktop remotely as well?

**Comment by matenavay** [comment]
Hi Tom,
sorry for not checking these before.
The current version only supports an SSH console through the browser, but we've started to make some prototypes where the GUI would be accessible as well.
The main advantages of the current solution are being super simple and very secure, as there is not much needed to be set up on the linux host.

**Comment by flexicon33** [comment]
Hi, could you explain more? I have access working and it opens an SSH window. How do I get the desktop view to appear, or should it have happened automatically? I followed the install procedure and vnc is running on the host. I am trying to connect thru the LogMeIn client.

**Comment by matenavay** [comment]
Hi,

The current version of the linux host only supports SSH terminal access.
We are working on a version with noVNC integrated that would allow desktop UI access, but that still needs a bit of work.

Regards,
Mate Navay - product manager
________________________________
